### ISSUE TITLE
大哥，第一步就报错了

### ISSUE THREAD

**Issue by fatcarter** [lsbFlying/resy#1]
const store = createStore({count:0});

count:0 部分提示 count does not exist in type () => never

**Comment by lsbFlying** [comment]
感谢老哥的尝试，但是你这个应该是代码编辑器的TS类型校验出了点问题，我在webStorm、vscode上并没有出现过这种类型校验报错提示，是否是项目本身的TS版本问题导致的呢，可否将项目代码地址我来具体看看

**Comment by fatcarter** [comment]
[这里](https://github.com/fatcarter/resy-reproduction)

按照下面的顺序

新建一个目录，执行下面的命令，然后编辑index.ts文件
```shell
cd dir

npm init 

tsc --init 

yarn add resy

touch index.ts

```


<img width="854" alt="image" src="https://github.com/lsbFlying/resy/assets/96217218/6ba7d425-e0db-47e8-a8d2-127621f935a3">

**Comment by lsbFlying** [comment]
这太简易了，你使用cra创建一个正常的项目demo在里面使用resy应该是正常的，你简单创建的demo-index.ts文件缺乏大部分正常项目的TS配置，你可以点进去resy内部的resy.d.ts声明文件，你应该可以在你的简易demo里面发现resy.d.ts声明文件里面的不少类型报红，都是缺乏正常项目配置导致的

**Comment by fatcarter** [comment]
并没有哦，使用10.0.2版本没有问题，我是用rn项目里面，下面是rn的ts配置


@react-native/typescript-config/tsconfig.json
```json

{
    "$schema": "https://json.schemastore.org/tsconfig",
    "display": "React Native",
    "compilerOptions": {
      "target": "esnext",
      "module": "es2015",
      "types": ["react-native", "jest"],
      "lib": [
        "es2019",
        "es2020.bigint",
        "es2020.date",
        "es2020.number",
        "es2020.promise",
        "es2020.string",
        "es2020.symbol.wellknown",
        "es2021.promise",
        "es2021.string",
        "es2021.weakref",
        "es2022.array",
        "es2022.object",
        "es2022.string"
      ],
      "allowJs": true,
      "jsx": "react-native",
      "noEmit": true,
      "isolatedModules": true,
      "strict": true,
      "moduleResolution": "bundler",
      "customConditions": ["react-native"],
      "allowImportingTsExtensions": true,
      "allowArbitraryExtensions": true,
      "resolveJsonModule": true,
      "resolvePackageJsonImports": false,
      "allowSyntheticDefaultImports": true,
      "esModuleInterop": true,
      "skipLibCheck": true,
      // Causes issues with package.json "exports"
      "forceConsistentCasingInFileNames": false
    },
    "exclude": [
      "node_modules",
      "babel.config.js",
      "metro.config.js",
      "jest.config.js"
    ]
  }

```

./tsconfig.json
```json
{
  "extends": "@react-native/typescript-config/tsconfig.json",
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@/*": ["src/*"]
    }
  }
}
```

**Comment by lsbFlying** [comment]
感谢老哥的提醒，10.0.2的类型校验比较宽松，11版本的类型校验加强了，但是可能针对项目配置会有些要求，可能是这些加强性的TS类型校验导致的，11相较于10版本破坏性升级重要在于10版本里面的view（可以理解为memo的效果）这个api被遗弃了，所以10版本也是大版本较为稳定，可以先用，感谢老哥尝试我做的螃蟹🦀️，我会尽快紧急查清并修复类型校验的问题；

**Comment by lsbFlying** [comment]
嗨大佬你好，我刚用你的RN项目的TS配置放在了自己的RN项目里面使用，发现了跟你一样的问题，我仔细检查了一下发现是因为你的ts配置略低，你需要把你的compilerOptions中的lib配置添加上"DOM" 与 "ESNext" 这两项，来保持JS的版本较新程度的使用；

补充：之所以需要加上DOM是忘了考虑RN中没有window的情况，类型上我会去除Window即可，后续版本我会立即更新ts类型

**Comment by lsbFlying** [comment]
V110.01-beta.1版本中更新调整了RN类型的校验（The RN type check has been updated and adjusted in the V110.01-beta.1 version.）
