### ISSUE TITLE
在action中修改状态控制台会抛出错误

### ISSUE THREAD

**Issue by fatcarter** [lsbFlying/resy#2]
reproduction： https://codesandbox.io/p/sandbox/resy-hook-reproduction-mhjf9d
count可以正常新增，页面也会更新，但是控制台会抛出错误
`The outer function of increment is used as a hook state, but it does not comply with the hook usage rules. Please check if the outer function where increment is called is being destructured inside useStore or useConciseState. If the outer function of increment does not need to be used as a hook state, then please call it directly through the store.
`

![image](https://github.com/lsbFlying/resy/assets/96217218/3d02abc5-bf5a-492f-89f7-742fd529a305)
我哪里使用的不对吗

**Comment by lsbFlying** [comment]
其实这里的警告报错是我抛出来给予开发者提示作用的，源于我对于函数属性的使用考量：

我在11版本中认为函数属性如果是需要针对state有对应更新，那么函数属性内部的this是指向你的appStore的；本身由于appStore是具有re-render更新效应的store，所以这里increment函数内部的this就是指向appStore；同时this.count就相当于使用了
`const [count] =  useState()`
所以此时你的handleBtnClick点击调用的时候就会产生hook规则报错，所以实际上这个报错是不符合hook规范的提示，但是我内部给予了异常捕捉的额外处理，所以你的页面可以正常更新，但是极其复杂的场景下可能也无法完善错误捕捉的场景；

实际上你只需要把increment通过store来调用就不会产生错误提示了，因为store本身不具备re-render特性，而通过useStore处理的appStore是真正能更新渲染的store；所以通过store.increment()一般而言是action的正常操作，不需要从useStore中解构或者读取action使用；因为从useStore中解构读取的数据本身会被认为是state状态；

但是事实上你这里的报错提示我也在考虑更加合理的处理方式，我的同事在使用的时候遇到这个报错也会变得懵逼，我想我需要一个更好的更和谐温和的处理方式，这也是我在下一个版本11.0.1的主要改进目标；

感谢兄弟还能给我提几个issue😊

**Comment by fatcarter** [comment]
最近刚接触react，hook还不是特别了解

对于上面的回答和上面代码我尝试着理解是tsx中引用的属性需要来自appStore, 但是action的调用需要通过store来调用

如果是这样子的话，感觉有点反人类，毕竟作为用户来讲，需要维护两个状态，很容易用错

我以前接触过vue和pinia，感觉很好用也很简洁，react这边状态管理一大堆，用了几个，感觉没一个比pinia好用（个人理解）

感觉resy和pinia很像，感觉api可以参考pinia的设计，再有一个我真的很需要在store中存在计算属性，不然我要写好多个useEffect 
T_T

**Comment by lsbFlying** [comment]
你说的很对，我也了解pinia，而resy也正是对标pinia设计的，vue相对于react的生态要和谐太多了，事实上vue使用自身的状态管理能力就足够了，很佩服vue的相关配置生态，但是react有它自身的开创性同时也有更多的局限性，很难评价两者，但是就你说的这一点而言react做的不够好，vue中没有类似react的hook那样的使用规则，所以react本身的hook使用规则对不知情的开发者而言心智负担还是略多，我也正在打算创建一个能降低这种使用上的心智负担的resy新版本（解决react的hook使用规则的心智负担），对于你说的计算属性，在新的11的beta版本中就是加入了这样的特性，我上一个回复中更多的可以抽象理解为：
函数属性放在useStore中解构使用就是相当于计算属性；而如果单纯的通过store使用就是相当于action；
举个例子：

```
const store = createStore({
  count: 0,
  countChange() {
    this.count = 999;
  },
  text: "ok",
  getTextPro() {
    // 如果是作为计算属性（即函数getTextPro通过useStore解构读取）
    // 那么这里的this相当于你之前写的appStore，就需要满足hook的使用规则（在顶层使用-可以查阅react官方文档也是说需要在顶层使用）
    const { text } = this;
    return `${text}_world`;
  },
});

export default function App() {
  const { count, getTextPro } = useStore(store);
  
  return (
    <div>
      <div>count:{count}</div>
      {/* 只不过与vue或者pinia中的计算属性不同的是，resy对于这种特性采取了贴合原生JS的理解特性，计算属性终究是函数，所以这里也是采用函数的调用方式 */}
      <div>textPro:{getTextPro()}</div>
      <button onClick={() => {
        // countChange不作为计算属性，不需要从useStore中解构使用，直接通过store调用，就作为action使用
        store.countChange();
      }}>countChange</button>
      <button onClick={() => {
        // 这里更新text的时候，getTextPro就充当计算属性，会更新渲染App组件
        store.text = "hello";
      }}>textChange</button>
    </div>
  );
}
```
您可以简单看一下我这个demo，尝试理解一下

**Comment by fatcarter** [comment]
嗯，demo理解了，在计算属性方面，作为服务端开发者认为做的不错。

针对你之前所说的increment函数中的this指向的是appStore，appStore是可以跟踪状态变化的对象，所以需要再顶层使用。

当store.increment()被调用后，从appStore中解构的count字段会重新渲染，那为了使用更加简洁为什么不能让函数属性的this指向store而不是appStore，这样我只需要管理appStore就好，而不是要同时管理store和appStore

**Comment by lsbFlying** [comment]
普通的action就是指向store的，只有当函数属性作为计算属性功能的时候（在useStore中解构读取）才指向appStore，通过store读取的数据仅仅是获取最新数据，它不具备appStore的更新效应，一般而言我们通过会使用解构使用；比如：
const { count } = useStore(store);
而很少使用
const appStore = useStore(store);
appStore.count;
而通过这种const { count } = useStore(store);用法事实上我们也不需要维护两套store，只需要关注store即可，这里就省略了appStore，也降低了维护成本与心智负担；

之所以这样设计是考虑到较为复杂的业务场景的情况下，store可能需要在各种难以想象到的地方使用，所以这里单独把store作为核心处理关注的对象；而非appStore，比如store需要在别的模块或组件中使用的情况下可以直接通过useStore(store)进行渲染，也可以使用store.count来获取最新数据进行业务逻辑的操作计算；这一点与pinia有所区别，pinia的defineStore返回的事实上就是appStore；它这么做使得defineStore返回的作为渲染层面可以在别的地方使用，但是在业务逻辑操作计算层面就不那么自由了，如果是逻辑操作计算层面，别的地方想使用defineStore的内部数据就只能在defineStore内部的action中继续添加，这会导致代码文件逐渐变得异常庞大，也会增加维护成本，我们认为代码行数不超过400行是常规的维护文件体积，核心还是defineStore的数据难以具备分享性，它只具备渲染的分享性；

补充：我觉得上面说的store不具有更新效应可能产生误解，就是正常使用store.count++;或者store.text = "new words";是可以使得组件得到更新渲染的，这里说的store不具有更新效应是指单纯的从store中解构读取数据不具备使得组件可以更新的能力，比如：

```
function App() {
  // 这里单纯的通过store读取数据，不能够使得App组件能够得到更新渲染re-render
  const { count, text } = store;
  
  return (
    <div>
      <div>count:{count}</div>
      <div>text:{text}</div>
      <button onClick={() => {
         store.setState({
            count: 9,
            text: "new words",
        });
      }}>change</button>
    </div>
  );
}
```

**Comment by fatcarter** [comment]
`
很少使用
const appStore = useStore(store); 
`
这部分应该是因人而异的吧，我就比较喜欢这样子用，因为这样可以很容易跟踪到变量的位置。

而且我发现，我可以在useEffect中使用useStore解构的参数，但是没法办用appStore.count；

对我来说，我在一个组件中不会只使用一个store，会有多个store，当store中出现重名属性时候，我必须要给每个属性起别名，我有强迫症，这对我来讲一点也不优雅;


上面说的我理解应该是想要在非react组件内使用store，如此对store的修改可能存在世界各地，我觉得这样不好，当有异常情况出现的时候很难排查问题的源头，就像打破单向数据流的感觉


至于会导致defineStore文件异常庞大的问题，我们可以将action的实现逻辑分散到不同的文件中，我觉的对于store的数据修改还是要加以管控，禁止随时随地store.count++这种操作

**Comment by lsbFlying** [comment]
你说的几点我是这样认为的：
1、跟踪到变量的位置：store同样可以追踪到变量的最新状态；
2、你给appStore起名为appStore的时候本身就是给store起别名了；优不优雅因人而异吧，导入的时候取别名我觉得也无伤大雅：import { store as loginStore } from "./login";
3、你说的将action的实现逻辑分散到不同的文件中本质上和你说的store的修改可能存在世界各地其实没什么差别，一个房间的整洁程度与房间的住户本身有关，其实说白了还是看开发者本人的代码管理程度；
4、store.count++这种操作事实上并不危险，按你所说如果是通过appStore.count++这样操作也无法保证代码的安全性，我可以把appStore通过props透传给任何子组件，或者通过回调返回给上层的任何父组件，所以本质上和你说store的修改可能存在世界各地是一样的，实质上还是看开发者本人的操作，当然你可以说appStore一定程度上限制了全世界任意修改状态的门槛，毕竟相对于透传或者回调而言都有一定的操作成本，这一点我是认同的；早期redux全部通过dispatch的action修改状态就是出于你说的这一点的考量；

但是针对这一点而言我本人的体会是比较深刻，开发至今遇到的问题多数较为复杂，我个人认为store的状态修改虽然带来了一定程度的危险性，同时也带来了一定程度的便利与优势；在复杂场景的操作交互中我认为它的优势甚至要大于它的危险劣势，store可以在任何地方简单便利的供你操作状态，当然这也是我个人的一点灼见，如果非要说这种危险性难以把控；事实上你也可以在resy的
```
createStore({
  count: 0,
  add() {
    this.count++;
  }
});
```
这样通过action的add方法进行更新操作，在代码风格规范约束上我是认同你的观点的，所以这样action操作事实上也是安全的；当然我基于上述我的原因描述还是略微激进的放开了store的状态更新能力，并且在实际项目开发中带来的收益远大于危险性的劣势，这是目前的同事反馈以及resy的开发体验🙏

**Comment by lsbFlying** [comment]
V11.0.1-beta.1版本中更新完善了“类计算属性”的功能（The functionally of "pseudo-computed property" has been updated and improved in the V11.0.1-beta.1 version.）
